### ISSUE TITLE
Feature request: Add the ability to use keyboard instead of controller

### ISSUE THREAD

**Issue by meteorfox** [zombieCraig/ICSim#1]
First of all, thank you for making this simulator.

I think it'd be great ICSim had the ability to use the keyboard instead of an external controller.It could be different combinations of keys. 

For example:

`s + left_arrow` - left turn signal
`s + right_arrow` - right turn signal
`s + up_arrow` -  hazard signal
`f + up_arrow` - increase fuel level
`f + down_arrow` - decrease fuel level
etc....

Additionally, there could also be a top level menu for Actuators, where  it has sub-menus for different sub-systems, each subystems has actions such as above.

**Comment by zombieCraig** [comment]
This already is in place.  The controls screen shows what keys to press.  Arrow keys (Up/Down) accelerates left/right turns...shift keys handle door operations.  I'm considering adding the ability to do ECU simulation for UDS requests but to make it work with the difficulty levels adds a hefty chunk of new code.

Make sure the control screen is highlighted and active when you use the keyboard.  Verify this works for me and I will close this ticket.  We use only keyboard access in the classroom and it works (at least with US keyboards)

**Comment by meteorfox** [comment]
Yes, you are right. I had to 'focus' the window. Thanks
