### ISSUE TITLE
Error DATA_DIR not found 

### ISSUE THREAD

**Issue by Enzosoft** [zombieCraig/ICSim#11]
Hi,
Sorry to bother with this but I'm quite new to Linux.
I got the instrument cluster sim to my system, no problem. It's in root/ICSim.
When I try to run the sim from the terminal I get error DATA_DIR not found.
I had a look in my files and the DATA_DIR folder is in the ICSim folder.
However when I try 'locate DATA_DIR' in the terminal I don't get any results. 

Any help is much appriciated.

**Comment by Grazfather** [comment]
Locate only finds files in your PATH variable.

You see that the data dir is ./data/, that means that you need to run icsim from the directory that contains it.

**Comment by Enzosoft** [comment]
Yes, sorry about that. Working great!
