### ISSUE TITLE
make will not compile on Raspberian

### ISSUE THREAD

**Issue by mrbrooks12** [zombieCraig/ICSim#2]
When make runs $gcc -I/... icsim.c lib.o ... it returns an error saying that the lib.o file will not run. If you know how could you please update the Makefile file or README.md to include how to compile and run ./icsim on a RaspberryPi 2? Thank you!

**Comment by zombieCraig** [comment]
Information on how to compile lib.o is now in the Readme https://github.com/zombieCraig/ICSim/blob/master/README.md
