### ISSUE TITLE
Can't fix read: bad address even with new SDL2 libraries when opening icsim and controls at the same time

### ISSUE THREAD

**Issue by e-magon** [zombieCraig/ICSim#22]
Hello
I'm using Ubuntu 18.04.5 LTE in VirtualBox
I downloaded this repo, followed the readme, compiled the program with no errors but when I tried to open controls and ICSim togheter, icsim crashed with the "read: bad address" error.

I tried to search here, and I've seen report of this bug with the fix being "recompile with the updated SDL2 libraries".
Installing sdl2-dev and sdl2-dev-image from apt got me the 2.0.8 version.

I tried to download the 2.0.12 version from the sdl website and I compiled it. I changed the MakeFile to use the 2.0.12 headers folder, I deleted the .o files and the compiled files and I run the make command,  but the error persists. I even tried to copy the libs from an Arch Linux installation but to no avail.

I don't know what to do next. Maybe using a newer version of Ubuntu with the SDL2 packages updated in the apt repos will help me?

Thank you

**Comment by zombieCraig** [comment]
Ubuntu 18.04 should be plenty new.  I also develop on Ubuntu, my current one is 18.04.  On a fresh 20.04 I did:
`git clone https://github.com/zombieCraig/ICSim`
`sudo apt install libsdl2-dev libsdl2-image-dev`
`make`
`./setup_vcan.sh`
`./controls vcan0` and `./icsim vcan0`
No apparent issues.  Can you confirm a similar process?

**Comment by OnlyRefat** [comment]
Hi @zombieCraig  I struggled with ubuntu 18.04 for the last 2 days. Finally, following your direction, the simulator worked like a charm on Ubuntu 20.04. Thanks a lot.

**Comment by e-magon** [comment]
> Hi @zombieCraig I struggled with ubuntu 18.04 for the last 2 days. Finally, following your direction, the simulator worked like a charm on Ubuntu 20.04. Thanks a lot.

I can confirm, trying it on the 20.04 LTE version like you did @zombieCraig works without problems.
I don't know why in Ubuntu 18, even with the latest SDL libraries, the error persisted, but I think I can mark this as resolved.

Thank you!
