### ISSUE TITLE
I got 404 error after this command "sudo apt-get install libsdl2-dev libsdl2-image-dev can-utils"

### ISSUE THREAD

**Issue by Daanav898** [zombieCraig/ICSim#31]
![Screenshot (42)](https://user-images.githubusercontent.com/82896084/144734665-a859290c-81f9-4548-af3e-b7bba774bde5.png)
![Screenshot (45)](https://user-images.githubusercontent.com/82896084/144734686-2696b420-35b3-41ef-bac3-c8337fe6377a.png)

That is the error. I am trying to install libsdl2-dev ,libsdl2-image-dev and can-utils packets but it can't complete my request plss help me to solve my issue #21

**Comment by collin80** [comment]
Those 404 errors are being returned by the Kali linux repo itself. You may need to run "apt-get update" to update your file list. It's possible that the version numbers now available are slightly different.
